[tool.poetry]
name = "monitor-agent"
version = "0.1.0"
description = "Monitor agent that sends and receives metrics and info from the REST API server."
authors = ["Pablo González Rubio <pjgr2000@gmail.com>"]
license = "GNU General Public License v3.0"
packages = [
    { include = "monitor-agent" },
    { include = "monitor-agent/**/*.py" },
]

[tool.poetry.scripts]
start = "monitor-agent.main:start"

[tool.poetry.dependencies]
python = ">=3.7,<4.0.0"
requests = "^2.27.1"
# https://python-poetry.org/docs/dependency-specification/#using-environment-markers
psutil = "^5.9.0"
fastapi = "^0.74.0"
uvicorn = "^0.17.4"
gunicorn = "^20.1.0"
pydantic = "^1.9.0"
timeloop = "^1.0.2"

[tool.poetry.dev-dependencies]
pytest = "^7.0.0"
tox = "^3.24.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
